pub mod app;
pub mod camera;
pub mod gpu;
pub mod mesh;
pub mod mesher;
pub mod net;
pub mod platform;
pub mod player;
pub mod renderer;
pub mod scene;
pub mod uniform;
pub mod vertex;

pub use app::App;

#[cfg(target_arch = "wasm32")]
use wasm_bindgen::prelude::*;

/// Explicit WASM entry point. `#[wasm_bindgen(start)]` tells the JS glue
/// generated by wasm-bindgen to call this function immediately after the
/// module is instantiated, before any other JS runs.
///
/// This replaces relying on Trunk's implicit `main()` detection, making
/// the entry point unambiguous to both the toolchain and future readers.
#[cfg(target_arch = "wasm32")]
#[wasm_bindgen(start)]
pub fn wasm_main() {
    let event_loop = winit::event_loop::EventLoop::new().unwrap();
    event_loop.set_control_flow(winit::event_loop::ControlFlow::Poll);
    let mut app = App::default();
    event_loop.run_app(&mut app).unwrap();
}
